### ISSUE TITLE
LightDM Greeter won't change background

### ISSUE THREAD

**Issue by uD4ra** [budgie-remix/budgie-remix-lightdm-theme#5]
**Lightdm Greeter won't change background** when changing it using `Settings > Background  > Lock Screen`

![screenshot from 2016-07-13 08-58-26](https://cloud.githubusercontent.com/assets/12265797/16792658/6cb0c124-48db-11e6-91f7-977802020248.png)

It's possible to change it using `lightdm-gtk-greeter-settings` and Wallpaper should be in `/usr/share/Backgroungs` other directories are not working.

**Comment by carlosqsilva** [comment]
Same problem here...

**Comment by fossfreedom** [comment]
confirmed - this is due to budgie-desktop using gnome-screensaver which the background app does not support; GNOME-Shell uses their own lockscreen which is integrated with the background app.  It is not possible to unpick this and use with another distro such as budgie-remix.

There are tentative thoughts upstream to reinvigorate the gnome-screensaver  project and therefore support budgie-desktop correctly.

**Comment by fossfreedom** [comment]
Fixed this at 17.10
